# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-14 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0008_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='email',
            new_name='email_from',
        ),
        migrations.AddField(
            model_name='message',
            name='email_to',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
